#!/bin/sh

# CLEAN OLD BUILD FILES
./clean -o -m -f

# SET COMPILER FLAGS
. ./set_flags
echo "Preprocessor Flags:"
echo "  $PREP_FLAGS"
echo "Compiler Flags:"
echo "  $COMP_FLAGS"

# COMMON MODULES
cp ../common/Kinds.f90 Kinds.f90
cp ../common/Utilities.f90 Utilities.f90
cp ../common/Gauss_Legendre_w_a.f90 Gauss_Legendre_w_a.f90
cp ../common/Quadratures.f90 Quadratures.f90

gfortran $GFORT_FLAGS_o Kinds.f90
gfortran $GFORT_FLAGS_o Utilities.f90
gfortran $GFORT_FLAGS_o Gauss_Legendre_w_a.f90
gfortran $GFORT_FLAGS_o Quadratures.f90
