#!/bin/sh
SCR_PATH="../source/common/scripts/"
# CLEAN OLD BUILD FILES
${SCR_PATH}clean

# SET COMPILER FLAGS
. ${SCR_PATH}set_flags
. ${SCR_PATH}echo_flags

# COMMON MODULES
SRC_PATH="../source/common/"
FNAME="Kinds"; . ${SCR_PATH}compile_it
FNAME="Global"; . ${SCR_PATH}compile_it
FNAME="Utilities"; . ${SCR_PATH}compile_it

# ASTRO MODULES
SRC_PATH="../source/astro/"
FNAME="Astro_Utilities"; . ${SCR_PATH}compile_it

# MAIN CODE MODULES
SRC_PATH="../source/"
FNAME="Diverge_approx"; . ${SCR_PATH}compile_it
