#!/bin/sh
SCR_PATH="../source/common/scripts/"
# CLEAN OLD BUILD FILES
${SCR_PATH}clean

# SET COMPILER FLAGS
. ${SCR_PATH}set_flags
. ${SCR_PATH}echo_flags

# COMMON MODULES
SRC_PATH="../source/common/"
FNAME="Kinds"; . ${SCR_PATH}compile_it
FNAME="Global"; . ${SCR_PATH}compile_it
FNAME="Utilities"; . ${SCR_PATH}compile_it
FNAME="FileIO_Utilities"; . ${SCR_PATH}compile_it
FNAME="Interpolation"; . ${SCR_PATH}compile_it
FNAME="Gauss_Legendre_w_a"; . ${SCR_PATH}compile_it
FNAME="Quadratures"; . ${SCR_PATH}compile_it

# ATMOSPHERE MODULES
SRC_PATH="../source/common/atmo/"
FNAME="USSA76"; . ${SCR_PATH}compile_it

# MAIN CODE MODULES
SRC_PATH="../source/"
FNAME="Atmospheres"; . ${SCR_PATH}compile_it
FNAME="Pathlengths"; . ${SCR_PATH}compile_it
