#!/bin/sh
SCR_PATH="../source/common/scripts/"
# CLEAN OLD BUILD FILES
${SCR_PATH}clean

# SET COMPILER FLAGS
. ${SCR_PATH}set_flags
. ${SCR_PATH}echo_flags

# MAIN CODE MODULES
SRC_PATH="../source/"
FNAME="Diverge_exact"; . ${SCR_PATH}compile_it
