#!/bin/sh

# CLEAN OLD BUILD FILES
./clean -o -m -f

# SET COMPILER FLAGS
. ./set_flags
echo "Preprocessor Flags:"
echo "  $PREP_FLAGS"
echo "Compiler Flags:"
echo "  $COMP_FLAGS"

# COMMON MODULES
cp ../common/Kinds.f90 Kinds.f90
cp ../common/Utilities.f90 Utilities.f90
cp ../common/Root_Solvers.f90 Root_Solvers.f90

gfortran $GFORT_FLAGS_o Kinds.f90
gfortran $GFORT_FLAGS_o Utilities.f90
gfortran $GFORT_FLAGS_o Root_Solvers.f90
