#!/usr/bin/sh

if [ $# -eq 0 ]
then
        echo "No clean option specified: Nothing cleaned."
        echo "(run $0 -h for help)"
        exit 0
fi

ECHO="false"

while getopts "omfh" OPTION; do
        case $OPTION in
                o)
                        find . -name "*.o" -type f -delete
                        ;;
                m)
                        find . -name "*.mod" -type f -delete
                        ;;
                f)
                        find . -name "*.f90" -type f -delete
                        ;;
                h)
                        echo "Usage:  ./clean [-o] [-m] [-f]"
                        echo ""
                        echo "   -o     removes all *.o   files"
                        echo "   -m     removes all *.mod files"
                        echo "   -f     removes all *.f90 files"
                        exit 0
                        ;;
        esac
done
