#!/bin/sh

# CLEAN OLD BUILD FILES
./clean -o -m -f

# SET COMPILER FLAGS
. ./set_flags
echo "Preprocessor Flags:"
echo "  $PREP_FLAGS"
echo "Compiler Flags:"
echo "  $COMP_FLAGS"

# COMMON MODULES
cp ../common/Kinds.f90 Kinds.f90
cp ../common/Global.f90 Global.f90
cp ../common/Utilities.f90 Utilities.f90

gfortran $GFORT_FLAGS_o Kinds.f90
gfortran $GFORT_FLAGS_o Global.f90
gfortran $GFORT_FLAGS_o Utilities.f90

# ASTRO MODULES
cp ../astro/Astro_Utilities.f90 Astro_Utilities.f90
gfortran $GFORT_FLAGS_o Astro_Utilities.f90
