#!/bin/sh

# CLEAN OLD BUILD FILES
./clean -o -m -f

# SET COMPILER FLAGS
. ./set_flags
echo "Preprocessor Flags:"
echo "  $PREP_FLAGS"
echo "Compiler Flags:"
echo "  $COMP_FLAGS"

# MAIN CODE MODULES
cp ../Diverge_exact.f90 Diverge_exact.f90
gfortran $GFORT_FLAGS_o Diverge_exact.f90