#!/usr/bin/sh

# CLEAN OLD BUILD FILES
#./cleanALL
./clean -o -m -f

# COMPILER FLAGS
# Peprocessor definitions for conditional compilation:
#  - Operating System (default Windows, -DLIN_OS specifies Linux)
#  - Intel MKL PRNGs (default off, -DIMKL specifies use Intel MKL)
#  - Coarray support (default off, -DCAF enables coarrays)
PREP_FLAGS="-cpp -DLIN_OS"
GFORT_FLAGS_DEBUG="${PREP_FLAGS} -Og -fmax-errors=5 -Wall -ffree-line-length-0 -fimplicit-none -fcheck=all -pedantic -fbacktrace -fcoarray=none"
GFORT_FLAGS_o="${GFORT_FLAGS_DEBUG} -c"

# COMMON MODULES
cp ../common/Kinds.f90 Kinds.f90
cp ../common/Global.f90 Global.f90
cp ../common/Utilities.f90 Utilities.f90
cp ../common/FileIO_Utilities.f90 FileIO_Utilities.f90
cp ../common/Interpolation.f90 Interpolation.f90
cp ../common/Legendre_Utilities.f90 Legendre_Utilities.f90
cp ../common/Sorting.f90 Sorting.f90
cp ../common/Random_Numbers.f90 Random_Numbers.f90
cp ../common/Statistics.f90 Statistics.f90
cp ../common/Root_Solvers.f90 Root_Solvers.f90
cp ../common/Gauss_Legendre_w_a.f90 Gauss_Legendre_w_a.f90
cp ../common/Quadratures.f90 Quadratures.f90

gfortran $GFORT_FLAGS_o Kinds.f90
gfortran $GFORT_FLAGS_o Global.f90
gfortran $GFORT_FLAGS_o Utilities.f90
gfortran $GFORT_FLAGS_o FileIO_Utilities.f90
gfortran $GFORT_FLAGS_o Interpolation.f90
gfortran $GFORT_FLAGS_o Legendre_Utilities.f90
gfortran $GFORT_FLAGS_o Sorting.f90
gfortran $GFORT_FLAGS_o Random_Numbers.f90
gfortran $GFORT_FLAGS_o Statistics.f90
gfortran $GFORT_FLAGS_o Root_Solvers.f90
gfortran $GFORT_FLAGS_o Gauss_Legendre_w_a.f90
gfortran $GFORT_FLAGS_o Quadratures.f90

#ASTRO MODULES
cp ../astro/Astro_Utilities.f90 Astro_Utilities.f90
gfortran $GFORT_FLAGS_o Astro_Utilities.f90

#ATMOSPHERE MODULES
cp ../atmo/USSA76.f90 USSA76.f90
gfortran $GFORT_FLAGS_o USSA76.f90

#PARTICLE UTILITIES MODULES
cp ../cs/Neutron_Utilities.f90 Neutron_Utilities.f90
cp ../cs/n_Cross_Sections.f90 n_Cross_Sections.f90

gfortran $GFORT_FLAGS_o Neutron_Utilities.f90
gfortran $GFORT_FLAGS_o n_Cross_Sections.f90

#MAIN CODE MODULES
cp ../Setups.f90 Setups.f90

gfortran $GFORT_FLAGS_o Setups.f90
