#!/bin/sh

# CLEAN OLD BUILD FILES
./clean -o -m -f

# SET COMPILER FLAGS
. ./set_flags
echo "Preprocessor Flags:"
echo "  $PREP_FLAGS"
echo "Compiler Flags:"
echo "  $COMP_FLAGS"

# COMMON MODULES
cp ../common/Kinds.f90 Kinds.f90
cp ../common/FileIO_Utilities.f90 FileIO_Utilities.f90
cp ../common/Sorting.f90 Sorting.f90
cp ../common/Random_Numbers.f90 Random_Numbers.f90
cp ../common/Statistics.f90 Statistics.f90

gfortran $GFORT_FLAGS_o Kinds.f90
gfortran $GFORT_FLAGS_o FileIO_Utilities.f90
gfortran $GFORT_FLAGS_o Sorting.f90
gfortran $GFORT_FLAGS_o Random_Numbers.f90
gfortran $GFORT_FLAGS_o Statistics.f90
