#!/bin/sh

# Peprocessor definitions for conditional compilation:
#  - Operating System (default Windows, -DLIN_OS for Linux)
#  - Intel MKL PRNGs (default off, -DIMKL for Intel MKL)
#  - Coarray support (default off, -DCAF enables coarrays)
#  - Compiler vendor (default gFortran, -DIFORT for Intel)
PREP_FLAGS="-cpp -DLIN_OS";

# Debug Compiler Flags
COMP_FLAGS="-Og -fmax-errors=5 -Wall -ffree-line-length-0 -fimplicit-none -fcheck=all -pedantic -fbacktrace -fcoarray=none"

# Release Compiler Flags
# COMP_FLAGS="-Ofast -ffree-line-length-0 -fimplicit-none -fcoarray=none"

GFORT_FLAGS="${PREP_FLAGS} ${COMP_FLAGS}"
GFORT_FLAGS_o="${GFORT_FLAGS} -c"